package Model;
public enum PlayerState {
    STANDING, WALK_UP, WALK_DOWN, WALK_LEFT, WALK_RIGHT,
    ATTACK_UP, ATTACK_DOWN, ATTACK_RIGHT, ATTACK_LEFT,
    SHOOT_UP, SHOOT_DOWN, SHOOT_RIGHT, SHOOT_LEFT, DEAD, PAUSE
}
